name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: go to server and run test
        run: |
          cd ./server
          dir
          $env:CC_RUN_SERVER="false"; npm test
