name: GitHub Actions Demo
on: [push]
jobs:
  Test-Server:
    runs-on: self-hosted
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: go to server and run test
        run: |
          pushd ./server
          dir
          $env:CC_RUN_SERVER="false"; npm test
          popd
  Test-App:
    runs-on: self-hosted
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: go to web-app
        run: |
          pushd ./web-app
      - name: run web-app and cypress test
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        with:
          build: npm run build
          start: npm start
      - name: back to main dir
        run: |
          popd
