name: GitHub Actions Demo
on: [push]
jobs:
  Test-Server:
    runs-on: self-hosted
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: go to server and run test
        run: |
          pushd ./server
          dir
          $env:CC_RUN_SERVER="false"; npm test
          popd
  Test-App:
    runs-on: self-hosted
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: go to server and run test
        run: |
          pushd ./web-app
          dir
          npx cypress run
          popd
